language: rust
cache: cargo
dist: trusty
os: linux
# sudo and addon only for codecov
sudo: true
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
      - libiberty-dev
      - zlib1g-dev
      - libudev-dev

# Run builds for all the supported trains
rust:
  - nightly
  - beta
  - stable

# Update distribution packages before anything else.
before_install:
  - sudo apt-get update

before_script:
  - cargo install diesel_cli --no-default-features --features sqlite --force

# The main build
script:
  - make build
  - make build-release
  - make package

after_success:
    # Coverage report
  - |
      if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_RUST_VERSION" == "stable" ]]; then
        wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz &&
        tar xzf master.tar.gz &&
        cd kcov-master &&
        mkdir build &&
        cd build &&
        cmake .. &&
        make &&
        sudo make install &&
        cd ../.. &&
        rm -rf kcov-master &&
        pwd &&
        ls -l /home/travis/build/yfery/octopod/target/release/ &&
        mkdir -p "target/cov/octopod/" 
        kcov --exclude-pattern=/.cargo,/usr/lib --verify "target/cov/octopod/" "target/debug/octopod" &&
        bash <(curl -s https://codecov.io/bash) &&
        echo "Uploaded code coverage"
      fi

notifications:
  email:
    recipients:
      - yann@fery.me
    on_success: change
    on_failure: always
