language: rust
cache: cargo
dist: trusty
os: 
  - linux

# Run builds for all the supported trains
rust:
  - nightly
  - beta
  - stable

before_script:
  - cargo install diesel_cli --no-default-features --features sqlite

# The main build
script:
  - make build-release
  - make package
